springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onboardme
#    url: jdbc:mysql://host.docker.internal:3306/onboardme
    username: root
    password: admin
    #url: jdbc:mysql://onboardme-db.c818gawim1nm.us-east-1.rds.amazonaws.com:3306/onboardme
    #username: admin
    #password: Onboardme2025!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: create-drop  # use `none`, `validate`, `update`, or `create-drop`
    show-sql: true       # show SQL queries in the console
    properties:
      hibernate:
        format_sql: true # pretty-print SQL in logs
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: juancruzcaggiano@gmail.com
    password: djyj rsoy zzwa nath
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Optional: logging settings for SQL (can help during dev)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

